import { Calendar, Clock, User, CheckSquare, AlertTriangle, Building, Phone } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useQuery } from "@tanstack/react-query";

interface TodayAppointment {
  id: string;
  time: Date;
  customerName: string;
  vehicleInfo: string;
  serviceType: string;
  isVip: boolean;
  status: 'scheduled' | 'arrived' | 'in_service' | 'completed';
}

interface ManagerTasks {
  hqTasks: Array<{id: string; title: string; priority: 'high' | 'medium' | 'low'; dueDate: Date}>;
  autoGenerated: Array<{id: string; title: string; type: 'equipment' | 'follow_up' | 'compliance'; dueDate: Date}>;
}

function AppointmentCard({ appointment }: { appointment: TodayAppointment }) {
  const getStatusConfig = (status: string) => {
    switch (status) {
      case 'completed':
        return { color: 'bg-green-100 dark:bg-green-950/20 text-green-800 dark:text-green-200', badge: 'default', text: 'Completed' };
      case 'in_service':
        return { color: 'bg-blue-100 dark:bg-blue-950/20 text-blue-800 dark:text-blue-200', badge: 'default', text: 'In Service' };
      case 'arrived':
        return { color: 'bg-orange-100 dark:bg-orange-950/20 text-orange-800 dark:text-orange-200', badge: 'secondary', text: 'Arrived' };
      default:
        return { color: 'bg-gray-100 dark:bg-gray-950/20 text-gray-800 dark:text-gray-200', badge: 'outline', text: 'Scheduled' };
    }
  };

  const statusConfig = getStatusConfig(appointment.status);
  const appointmentTime = new Date(appointment.time);
  const isUpcoming = appointmentTime > new Date();
  const timeDisplay = appointmentTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  return (
    <Card className={`border-l-4 ${appointment.isVip ? 'border-l-yellow-500' : 'border-l-blue-500'} ${statusConfig.color}`} data-testid={`appointment-${appointment.id}`}>
      <CardContent className="p-4">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <Clock className="h-4 w-4" />
            <span className="font-bold text-sm">{timeDisplay}</span>
            {appointment.isVip && (
              <Badge variant="secondary" className="bg-yellow-200 text-yellow-800 dark:bg-yellow-800 dark:text-yellow-200 text-xs">
                VIP
              </Badge>
            )}
          </div>
          <Badge variant={statusConfig.badge as any} className="text-xs">
            {statusConfig.text}
          </Badge>
        </div>
        
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <User className="h-3 w-3 opacity-60" />
            <span className="font-medium text-sm">{appointment.customerName}</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted-foreground">{appointment.vehicleInfo}</span>
          </div>
          <div className="text-xs text-muted-foreground">
            {appointment.serviceType}
          </div>
        </div>

        {appointment.status === 'scheduled' && isUpcoming && (
          <div className="mt-3 flex gap-2">
            <Button variant="outline" size="sm" className="h-6 px-2 text-xs">
              Notify Arrival
            </Button>
            <Button variant="outline" size="sm" className="h-6 px-2 text-xs">
              Reschedule
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function TaskCard({ 
  task, 
  type = 'hq' 
}: { 
  task: {id: string; title: string; priority?: 'high' | 'medium' | 'low'; type?: string; dueDate: Date}; 
  type?: 'hq' | 'auto' 
}) {
  const getPriorityConfig = (priority: string = 'medium') => {
    switch (priority) {
      case 'high':
        return { color: 'border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-950/20', badge: 'destructive', icon: AlertTriangle };
      case 'low':
        return { color: 'border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-950/20', badge: 'default', icon: CheckSquare };
      default:
        return { color: 'border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-950/20', badge: 'secondary', icon: CheckSquare };
    }
  };

  const getTypeIcon = (taskType: string = '') => {
    switch (taskType) {
      case 'equipment': return CheckSquare;
      case 'follow_up': return Phone;
      case 'compliance': return Building;
      default: return CheckSquare;
    }
  };

  const config = getPriorityConfig(task.priority);
  const Icon = type === 'hq' ? config.icon : getTypeIcon(task.type);
  const dueDate = new Date(task.dueDate);
  const isOverdue = dueDate < new Date();
  const isToday = dueDate.toDateString() === new Date().toDateString();

  return (
    <Card className={`border-l-4 ${config.color} ${isOverdue ? 'border-l-red-500' : ''}`} data-testid={`task-${task.id}`}>
      <CardContent className="p-4">
        <div className="flex items-start justify-between mb-2">
          <div className="flex items-start gap-2 flex-1">
            <Icon className="h-4 w-4 mt-0.5 text-muted-foreground" />
            <div className="flex-1 min-w-0">
              <h4 className="font-medium text-sm leading-tight">{task.title}</h4>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-xs text-muted-foreground">
                  Due: {isToday ? 'Today' : dueDate.toLocaleDateString()}
                </span>
                {isOverdue && (
                  <Badge variant="destructive" className="text-xs">
                    Overdue
                  </Badge>
                )}
              </div>
            </div>
          </div>
          {type === 'hq' && task.priority && (
            <Badge variant={config.badge as any} className="text-xs ml-2">
              {task.priority}
            </Badge>
          )}
        </div>
        
        <Button variant="outline" size="sm" className="w-full h-6 text-xs mt-2">
          {type === 'hq' ? 'View Details' : 'Complete Task'}
        </Button>
      </CardContent>
    </Card>
  );
}

export default function AppointmentTasksPanel() {
  const { data: appointments, isLoading: appointmentsLoading } = useQuery<TodayAppointment[]>({
    queryKey: ["/api/manager/appointments/today"],
    refetchInterval: 60000, // Refresh every minute
  });

  const { data: tasks, isLoading: tasksLoading } = useQuery<ManagerTasks>({
    queryKey: ["/api/manager/tasks"],
    refetchInterval: 300000, // Refresh every 5 minutes
  });

  const isLoading = appointmentsLoading || tasksLoading;

  if (isLoading) {
    return (
      <Card className="h-full">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Calendar className="h-5 w-5 text-purple-500" />
            Today's Schedule & Tasks
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <div key={i} className="h-24 bg-gray-200 dark:bg-gray-700 rounded-lg animate-pulse"></div>
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  const upcomingAppointments = (appointments || []).filter(apt => new Date(apt.time) > new Date()).slice(0, 3);
  const hqTasks = (tasks?.hqTasks || []).slice(0, 3);
  const autoTasks = (tasks?.autoGenerated || []).slice(0, 2);

  return (
    <Card className="h-full">
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Calendar className="h-5 w-5 text-purple-500" />
            Schedule & Tasks
          </div>
          <Badge variant="outline" className="text-xs">
            {(appointments || []).length} appointments • {(hqTasks.length + autoTasks.length)} tasks
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6 max-h-96 overflow-y-auto">
        {/* Today's Appointments */}
        <div className="space-y-3">
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider">
            Upcoming Appointments
          </h3>
          {upcomingAppointments.length === 0 ? (
            <div className="text-center py-4 text-muted-foreground">
              <Calendar className="h-6 w-6 mx-auto mb-2 opacity-50" />
              <p className="text-sm">No upcoming appointments</p>
            </div>
          ) : (
            <div className="space-y-3">
              {upcomingAppointments.map((appointment) => (
                <AppointmentCard key={appointment.id} appointment={appointment} />
              ))}
            </div>
          )}
        </div>

        {/* HQ Tasks */}
        <div className="space-y-3">
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider">
            HQ Tasks Assigned
          </h3>
          {hqTasks.length === 0 ? (
            <div className="text-center py-4 text-muted-foreground">
              <Building className="h-6 w-6 mx-auto mb-2 opacity-50" />
              <p className="text-sm">No HQ tasks assigned</p>
            </div>
          ) : (
            <div className="space-y-3">
              {hqTasks.map((task) => (
                <TaskCard key={task.id} task={task} type="hq" />
              ))}
            </div>
          )}
        </div>

        {/* Auto-Generated Tasks */}
        <div className="space-y-3">
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wider">
            System-Generated Tasks
          </h3>
          {autoTasks.length === 0 ? (
            <div className="text-center py-4 text-muted-foreground">
              <CheckSquare className="h-6 w-6 mx-auto mb-2 opacity-50" />
              <p className="text-sm">No system tasks pending</p>
            </div>
          ) : (
            <div className="space-y-3">
              {autoTasks.map((task) => (
                <TaskCard key={task.id} task={task} type="auto" />
              ))}
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}